### PR TITLE
lightning integrations work-in-progress (cannibalized by other merged PRs)

### PR DESCRIPTION
**Pull request by BitcoinMechanic**
will probably keep adding to this PR until all the wallets info here is updated, not just zeus.

### CODE REVIEW

**Comment by kn0wmad** [comment]
Maybe convert to a draft PR - request review when ready

**Comment by kn0wmad** [comment]
Need to test with CLN - will you also please change the link here to Firefox Beta in Play store (step 1) with this PR?  Apparently Firefox was never tested and does not work - https://docs.start9.com/latest/user-manual/connecting/connecting-tor/tor-firefox/torff-android

**Comment by BitcoinMechanic** [comment]
Might be better done in a different PR? This one could be quite some time yet

**Comment by BitcoinMechanic** [comment]
Yes, no longer relevant

**Pull request closed without merging**
