### PR TITLE
Update instructions for M1 macs

### PR DESCRIPTION
**Pull request by BitcoinMechanic**

### CODE REVIEW

**Review by MattDHill — CHANGES_REQUESTED** [review]
(1) steps 2 and 3 appear to be saying the same thing.

(2) there are links above steps 2 and 3 that are unnecessary and lead to a 404 page.

(3) there is an extra step needed for computers with Apple M1 chips. Here is the complete guide: https://mac.install.guide/homebrew/3.html

**Comment by BitcoinMechanic** [comment]
(1) 
Step 2 is password, step 3 is agreeing to the directories homebrew wants to create.

Am I misunderstanding?

(2)
Neither https://brew.sh/ or https://raw.githubusercontent.com/Homebrew/install/master/install.sh lead to 404 for me?

(3)
Thanks for those instructions. It looks like 

- Add Homebrew to your PATH in ~/.zprofile:
echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> ~/.zprofile
eval "$(/opt/homebrew/bin/brew shellenv)"

May be the only needed extra step for M1 macs. We can just add "This step might be necessary. To confirm if Brew is in your path type `which brew` and if it isn't, run the following." or something along those lines?

Sadly I can't confirm as I don't have an M1 mac, but I can get it tested none the less.

**Comment by MattDHill** [comment]
My original comments were based off the "preview" tab inside Github (see below), which cannot properly render restructured text. Disregard 1 and 2. 3 is still valid.

Screen Shot 2021-12-07 at 12 51 04 PM

**Comment by BitcoinMechanic** [comment]
I'm am going through step 3 with a friend with a vanilla M1 mac. We're documenting the process. Looks like password is necessary multiple times.

**Comment by BitcoinMechanic** [comment]
Looks like we'll have to add the instructions to add `brew` to path. Also required typing in password several times during install.

**Review by kn0wmad — COMMENTED** [review]
Was it determined that Rosetta was not required on the run-through you did with that vanilla Mac, or was it already on his machine?  @BitcoinMechanic 

I believe @chrisguida suggested this may be a dep

**Comment by chrisguida** [comment]
No, Rosetta is not required anymore. Homebrew has ported most of its packages to M1 native at this point. These are what go in your special M1 homebrew system folder, the one you add to your PATH with that command that pops out at the end of the homebrew install.

**Review by kn0wmad — APPROVED** [review]

**Comment by kn0wmad** [comment]
I'm going to merge this pending @MattDHill's acceptance of my dismissed review

**Comment by kn0wmad** [comment]
I think this is no longer valid - @BitcoinMechanic can you confirm?

**Comment by BitcoinMechanic** [comment]
Still unclear - I'll do some more testing

**Comment by chrisguida** [comment]
What has changed?

**Pull request closed without merging**
